
ALTER TABLE EMPLOYEE
ADD (MAX_SALARY NUMBER(7,2));

UPDATE EMPLOYEE
SET MAX_SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE)
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE);


DELETE FROM EMPLOYEE WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE)


CREATE INDEX DPR_NAME_IDX ON EMPLOYEE(SALARY);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT CNSTR_SALARY CHECK (SALARY >= 1000 AND SALARY <= 100000);

DROP INDEX DPR_NAME_IDX;

ALTER TABLE EMPLOYEE ENABLE CONSTRAINT CNSTR_SALARY;
ALTER TABLE EMPLOYEE DISABLE CONSTRAINT CNSTR_SALARY;
ALTER TABLE EMPLOYEE DROP CONSTRAINT CNSTR_SALARY;

CREATE TABLE EMP AS SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEE;

ALTER TABLE EMP
ADD (DEPARTMENT_NAME VARCHAR(100));

UPDATE EMP
SET DEPARTMENT_NAME = (
    SELECT DEPARTMENT_NAME
    FROM DEPARTMENTS
    WHERE EMP.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
)
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
);

MERGE INTO EMP E
USING (SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS) D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHEN MATCHED THEN
UPDATE SET
E.DEPARTMENT_NAME = D.DEPARTMENT_NAME
WHEN NOT MATCHED THEN
INSERT VALUES (D.DEPARTMENT_ID, D.DEPARTMENT_NAME);

DROP TABLE EMP;

WITH
EMP_S AS (
    SELECT E.FIRST_NAME, E.LAST_NAME, E.JOB_ID, E.DEPARTMENT_ID
    FROM EMPLOYEE E
    JOIN JOB J ON E.JOB_ID = J.JOB_ID
    WHERE J.JOB_TITLE LIKE 'S%'),
JOB_DETAILS AS (
    SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, JOB_ID FROM JOB),
DEP AS (
    SELECT DEPARTMENT_NAME, DEPARTMENT_ID FROM DEPARTMENTS)
SELECT
    EMP_S.FIRST_NAME || ' ' || EMP_S.LAST_NAME AS FULL_NAME,
    JOB_DETAILS.JOB_TITLE,
    JOB_DETAILS.MIN_SALARY,
    JOB_DETAILS.MAX_SALARY,
    DEP.DEPARTMENT_NAME
FROM EMP_S
JOIN JOB_DETAILS ON JOB_DETAILS.JOB_ID = EMP_S.JOB_ID
JOIN DEP ON EMP_S.DEPARTMENT_ID = DEP.DEPARTMENT_ID;

