-- 1
ALTER TABLE EMPLOYEES
ADD (MAX_SALARY NUMBER(7,2));

-- 2
UPDATE EMPLOYEES
SET MAX_SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES)
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES);

-- 3
DELETE FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

-- 4
CREATE INDEX EMP_SALARY_IDX ON EMPLOYEES(SALARY);

-- 5
ALTER TABLE EMPLOYEES
ADD CONSTRAINT CNSTR_SALARY CHECK (SALARY >= 1000 AND SALARY <= 100000);

-- 6
DROP INDEX EMP_SALARY_IDX;

-- 7
ALTER TABLE EMPLOYEES ENABLE CONSTRAINT CNSTR_SALARY;
ALTER TABLE EMPLOYEES DISABLE CONSTRAINT CNSTR_SALARY;
ALTER TABLE EMPLOYEES DROP CONSTRAINT CNSTR_SALARY;

-- 8
CREATE TABLE EMP AS SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- 9
ALTER TABLE EMP
ADD (DEPARTMENT_NAME VARCHAR(100));

-- 10
UPDATE EMP
SET DEPARTMENT_NAME = (
    SELECT DEPARTMENT_NAME
    FROM DEPARTMENTS
    WHERE EMP.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
)
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
);

-- 11
MERGE INTO EMP E
USING (SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS) D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHEN MATCHED THEN
UPDATE SET
E.DEPARTMENT_NAME = D.DEPARTMENT_NAME
WHEN NOT MATCHED THEN
INSERT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (D.DEPARTMENT_ID, D.DEPARTMENT_NAME);

-- 12
DROP TABLE EMP;

-- 13
WITH
EMP_S AS (
    SELECT E.FIRST_NAME, E.LAST_NAME, E.JOB_ID, E.DEPARTMENT_ID
    FROM EMPLOYEES E
    JOIN JOBS J ON E.JOB_ID = J.JOB_ID
    WHERE J.JOB_TITLE LIKE 'S%'),
JOB_DETAILS AS (
    SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, JOB_ID FROM JOBS),
DEP AS (
    SELECT DEPARTMENT_NAME, DEPARTMENT_ID FROM DEPARTMENTS)
SELECT
    EMP_S.FIRST_NAME || ' ' || EMP_S.LAST_NAME AS FULL_NAME,
    JOB_DETAILS.JOB_TITLE,
    JOB_DETAILS.MIN_SALARY,
    JOB_DETAILS.MAX_SALARY,
    DEP.DEPARTMENT_NAME
FROM EMP_S
JOIN JOB_DETAILS ON JOB_DETAILS.JOB_ID = EMP_S.JOB_ID
JOIN DEP ON EMP_S.DEPARTMENT_ID = DEP.DEPARTMENT_ID;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY, HIRE_DATE)
VALUES
(1, 'Ahmet', 'Yılmaz', 'IT_PROG', 10, 5000.00, TO_DATE('2020-01-15', 'YYYY-MM-DD')),
(2, 'Ayşe', 'Kara', 'HR_REP', 20, 4500.00, TO_DATE('2019-03-20', 'YYYY-MM-DD')),
(3, 'Mehmet', 'Demir', 'FIN_ANAL', 30, 5500.00, TO_DATE('2018-07-10', 'YYYY-MM-DD')),
(4, 'Fatma', 'Şahin', 'IT_PROG', 10, 6000.00, TO_DATE('2021-11-05', 'YYYY-MM-DD')),
(5, 'Ali', 'Öztürk', 'HR_REP', 20, 4700.00, TO_DATE('2017-09-30', 'YYYY-MM-DD'));

