
SELECT DEPARTMENT_ID, LISTAGG(FIRST_NAME || ' ' || LAST_NAME, '; ')
WITHIN GROUP (ORDER BY DEPARTMENT_ID) AS SONUC
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;


SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_ID,
    LAG(SALARY) OVER (PARTITION BY E.JOB_ID ORDER BY E.HIRE_DATE)
    + LEAD(SALARY) OVER (PARTITION BY E.JOB_ID ORDER BY E.HIRE_DATE)
    AS PREV_AFTER_SALARY_TOTAL
FROM EMPLOYEES E;


SELECT E.*, ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS ROW_ORDER
FROM EMPLOYEES E
WHERE NOT SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);


SELECT E.*, ROW_NUMBER() OVER (ORDER BY HIRE_DATE ASC) AS HIRE_ORDER
FROM EMPLOYEES E;


SELECT FIRST_NAME, LAST_NAME, SALARY,
    LAG(SALARY) OVER (ORDER BY HIRE_DATE) AS PREVIOUS_SALARY,
    LEAD(SALARY) OVER (ORDER BY HIRE_DATE) AS NEXT_SALARY
FROM EMPLOYEES;
